const { pg } = require("./db_connect.js")

const delete_all_tables = async () =>
    ["people"].forEach(e => pg.execute(`drop table if exists ${e}`));

const create_userbase = `\
CREATE TABLE people (\
    id int generated by default as identity primary key,\
    username text unique not null,\
    password text not null\
);
`

console.log("Hello");
//delete_all_tables();
console.log(pg.execute(create_userbase));